// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Set up encryption vault with a new passphrase.
/// Generates salt, derives key via Argon2id, persists KDF metadata.
/// Returns true on success.
Future<bool> vaultSetup({required String passphrase}) =>
    RustLib.instance.api.crateApiCryptoVaultSetup(passphrase: passphrase);

/// Unlock an existing vault with the passphrase.
/// Re-derives the key from stored salt, holds it in memory.
Future<bool> vaultUnlock({required String passphrase}) =>
    RustLib.instance.api.crateApiCryptoVaultUnlock(passphrase: passphrase);

/// Lock the vault — drops the in-memory key.
Future<bool> vaultLock() => RustLib.instance.api.crateApiCryptoVaultLock();

/// Returns vault status: enabled, passphraseSet, unlocked.
Future<VaultStatus> vaultStatus() =>
    RustLib.instance.api.crateApiCryptoVaultStatus();

/// Encrypt a file (plaintext -> .tdenc envelope).
Future<void> encryptFile({required String srcPath, required String dstPath}) =>
    RustLib.instance.api.crateApiCryptoEncryptFile(
      srcPath: srcPath,
      dstPath: dstPath,
    );

/// Decrypt a file (.tdenc envelope -> plaintext).
Future<void> decryptFile({required String srcPath, required String dstPath}) =>
    RustLib.instance.api.crateApiCryptoDecryptFile(
      srcPath: srcPath,
      dstPath: dstPath,
    );

class VaultStatus {
  final bool enabled;
  final bool passphraseSet;
  final bool unlocked;

  const VaultStatus({
    required this.enabled,
    required this.passphraseSet,
    required this.unlocked,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ passphraseSet.hashCode ^ unlocked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultStatus &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          passphraseSet == other.passphraseSet &&
          unlocked == other.unlocked;
}
