// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirror.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `db`

/// Opens (and migrates) the local database. Call once at app startup with the
/// path from `path_provider` (e.g. `getApplicationSupportDirectory`).
void initCore({required String dbPath}) =>
    RustLib.instance.api.crateApiDbInitCore(dbPath: dbPath);

/// Total non-trashed items (grid badge & boot summary).
PlatformInt64 countMedia() => RustLib.instance.api.crateApiDbCountMedia();

/// Keyset-paginated timeline (PRD Part 1 §11.3): pass `before_timestamp` from
/// the last item of the previous page to page forward without OFFSET.
List<MediaItem> listTimeline({
  PlatformInt64? beforeTimestamp,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiDbListTimeline(
  beforeTimestamp: beforeTimestamp,
  limit: limit,
);

Future<MediaItem?> getMedia({required String id}) =>
    RustLib.instance.api.crateApiDbGetMedia(id: id);

AppSettings getSettings() => RustLib.instance.api.crateApiDbGetSettings();

void saveSettings({required AppSettings settings}) =>
    RustLib.instance.api.crateApiDbSaveSettings(settings: settings);

VaultInfo getVaultInfo() => RustLib.instance.api.crateApiDbGetVaultInfo();

List<Upload> listUploadsByStatus({required String status}) =>
    RustLib.instance.api.crateApiDbListUploadsByStatus(status: status);

/// Backup banner aggregate (G4): one indexed GROUP BY.
UploadsSummary uploadsSummary() =>
    RustLib.instance.api.crateApiDbUploadsSummary();

String? getCaption({required String mediaId}) =>
    RustLib.instance.api.crateApiDbGetCaption(mediaId: mediaId);

void saveCaption({required String mediaId, required String text}) =>
    RustLib.instance.api.crateApiDbSaveCaption(mediaId: mediaId, text: text);

void addCaptionTag({required String mediaId, required String tag}) =>
    RustLib.instance.api.crateApiDbAddCaptionTag(mediaId: mediaId, tag: tag);

List<String> searchByHashtag({required String tag}) =>
    RustLib.instance.api.crateApiDbSearchByHashtag(tag: tag);

Collection createCollection({required String name}) =>
    RustLib.instance.api.crateApiDbCreateCollection(name: name);

List<Collection> listCollections() =>
    RustLib.instance.api.crateApiDbListCollections();

void addToCollection({required String collectionId, required String mediaId}) =>
    RustLib.instance.api.crateApiDbAddToCollection(
      collectionId: collectionId,
      mediaId: mediaId,
    );

void removeFromCollection({
  required String collectionId,
  required String mediaId,
}) => RustLib.instance.api.crateApiDbRemoveFromCollection(
  collectionId: collectionId,
  mediaId: mediaId,
);

List<MediaItem> listCollectionItems({required String collectionId}) => RustLib
    .instance
    .api
    .crateApiDbListCollectionItems(collectionId: collectionId);

List<Album> listAlbums() => RustLib.instance.api.crateApiDbListAlbums();
