// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `UploadError`

class Album {
  final String id;
  final String name;
  final PlatformInt64 createdAt;
  final String? coverMediaId;
  final bool isPinned;
  final String sourceType;
  final PlatformInt64 itemCount;

  const Album({
    required this.id,
    required this.name,
    required this.createdAt,
    this.coverMediaId,
    required this.isPinned,
    required this.sourceType,
    required this.itemCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      coverMediaId.hashCode ^
      isPinned.hashCode ^
      sourceType.hashCode ^
      itemCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Album &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          createdAt == other.createdAt &&
          coverMediaId == other.coverMediaId &&
          isPinned == other.isPinned &&
          sourceType == other.sourceType &&
          itemCount == other.itemCount;
}

class AppSettings {
  final bool autoBackupEnabled;
  final bool backupOverWifiOnly;
  final bool backupWhileChargingOnly;
  final bool uploadOriginalQuality;
  final Map<String, bool> folderBackupSettings;
  final bool clientEncryptionEnabled;
  final bool vaultPassphraseSet;
  final PlatformInt64 gridColumnCount;
  final String theme;
  final String? telegramApiId;
  final String? telegramApiHash;
  final String? googleClientId;
  final String? googleClientSecret;

  const AppSettings({
    required this.autoBackupEnabled,
    required this.backupOverWifiOnly,
    required this.backupWhileChargingOnly,
    required this.uploadOriginalQuality,
    required this.folderBackupSettings,
    required this.clientEncryptionEnabled,
    required this.vaultPassphraseSet,
    required this.gridColumnCount,
    required this.theme,
    this.telegramApiId,
    this.telegramApiHash,
    this.googleClientId,
    this.googleClientSecret,
  });

  @override
  int get hashCode =>
      autoBackupEnabled.hashCode ^
      backupOverWifiOnly.hashCode ^
      backupWhileChargingOnly.hashCode ^
      uploadOriginalQuality.hashCode ^
      folderBackupSettings.hashCode ^
      clientEncryptionEnabled.hashCode ^
      vaultPassphraseSet.hashCode ^
      gridColumnCount.hashCode ^
      theme.hashCode ^
      telegramApiId.hashCode ^
      telegramApiHash.hashCode ^
      googleClientId.hashCode ^
      googleClientSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppSettings &&
          runtimeType == other.runtimeType &&
          autoBackupEnabled == other.autoBackupEnabled &&
          backupOverWifiOnly == other.backupOverWifiOnly &&
          backupWhileChargingOnly == other.backupWhileChargingOnly &&
          uploadOriginalQuality == other.uploadOriginalQuality &&
          folderBackupSettings == other.folderBackupSettings &&
          clientEncryptionEnabled == other.clientEncryptionEnabled &&
          vaultPassphraseSet == other.vaultPassphraseSet &&
          gridColumnCount == other.gridColumnCount &&
          theme == other.theme &&
          telegramApiId == other.telegramApiId &&
          telegramApiHash == other.telegramApiHash &&
          googleClientId == other.googleClientId &&
          googleClientSecret == other.googleClientSecret;
}

class AuthCodeResult {
  final String status;
  final int? codeLength;
  final int? resendAfterSeconds;
  final String? delivery;

  const AuthCodeResult({
    required this.status,
    this.codeLength,
    this.resendAfterSeconds,
    this.delivery,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      codeLength.hashCode ^
      resendAfterSeconds.hashCode ^
      delivery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthCodeResult &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          codeLength == other.codeLength &&
          resendAfterSeconds == other.resendAfterSeconds &&
          delivery == other.delivery;
}

class Collection {
  final String id;
  final String name;
  final String? coverMediaId;
  final bool isCloud;
  final PlatformInt64 sortOrder;
  final PlatformInt64 createdAt;
  final PlatformInt64 itemCount;

  const Collection({
    required this.id,
    required this.name,
    this.coverMediaId,
    required this.isCloud,
    required this.sortOrder,
    required this.createdAt,
    required this.itemCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      coverMediaId.hashCode ^
      isCloud.hashCode ^
      sortOrder.hashCode ^
      createdAt.hashCode ^
      itemCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Collection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          coverMediaId == other.coverMediaId &&
          isCloud == other.isCloud &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt &&
          itemCount == other.itemCount;
}

class MediaItem {
  final String id;
  final String? localIdentifier;
  final String fileName;
  final String? filePath;
  final String mimeType;
  final String mediaType;
  final PlatformInt64 fileSizeBytes;
  final String sha256Hash;
  final PlatformInt64 dateTaken;
  final PlatformInt64 dateAdded;
  final PlatformInt64? width;
  final PlatformInt64? height;
  final PlatformInt64? orientation;
  final PlatformInt64? durationMs;
  final String? cameraMake;
  final String? cameraModel;
  final double? focalLength;
  final double? aperture;
  final PlatformInt64? iso;
  final String? exposureTime;
  final double? latitude;
  final double? longitude;
  final String? geoCity;
  final String? geoCountry;
  final String syncStatus;
  final PlatformInt64? uploadProgress;
  final String? errorMessage;
  final PlatformInt64? tgChannelId;
  final PlatformInt64? tgMessageId;
  final String? tgFileId;
  final PlatformInt64? tgAccessHash;
  final bool importedFromGooglePhotos;
  final String? googlePhotosMediaId;
  final String? googleCleanupStatus;
  final String? thumbnailPath;
  final String? previewPath;
  final String? blurHash;
  final bool isFavorite;
  final bool isArchived;
  final bool isTrashed;
  final PlatformInt64? trashedTimestamp;
  final bool isEncrypted;
  final List<String> albumIds;
  final String? deviceFolder;

  const MediaItem({
    required this.id,
    this.localIdentifier,
    required this.fileName,
    this.filePath,
    required this.mimeType,
    required this.mediaType,
    required this.fileSizeBytes,
    required this.sha256Hash,
    required this.dateTaken,
    required this.dateAdded,
    this.width,
    this.height,
    this.orientation,
    this.durationMs,
    this.cameraMake,
    this.cameraModel,
    this.focalLength,
    this.aperture,
    this.iso,
    this.exposureTime,
    this.latitude,
    this.longitude,
    this.geoCity,
    this.geoCountry,
    required this.syncStatus,
    this.uploadProgress,
    this.errorMessage,
    this.tgChannelId,
    this.tgMessageId,
    this.tgFileId,
    this.tgAccessHash,
    required this.importedFromGooglePhotos,
    this.googlePhotosMediaId,
    this.googleCleanupStatus,
    this.thumbnailPath,
    this.previewPath,
    this.blurHash,
    required this.isFavorite,
    required this.isArchived,
    required this.isTrashed,
    this.trashedTimestamp,
    required this.isEncrypted,
    required this.albumIds,
    this.deviceFolder,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      localIdentifier.hashCode ^
      fileName.hashCode ^
      filePath.hashCode ^
      mimeType.hashCode ^
      mediaType.hashCode ^
      fileSizeBytes.hashCode ^
      sha256Hash.hashCode ^
      dateTaken.hashCode ^
      dateAdded.hashCode ^
      width.hashCode ^
      height.hashCode ^
      orientation.hashCode ^
      durationMs.hashCode ^
      cameraMake.hashCode ^
      cameraModel.hashCode ^
      focalLength.hashCode ^
      aperture.hashCode ^
      iso.hashCode ^
      exposureTime.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      geoCity.hashCode ^
      geoCountry.hashCode ^
      syncStatus.hashCode ^
      uploadProgress.hashCode ^
      errorMessage.hashCode ^
      tgChannelId.hashCode ^
      tgMessageId.hashCode ^
      tgFileId.hashCode ^
      tgAccessHash.hashCode ^
      importedFromGooglePhotos.hashCode ^
      googlePhotosMediaId.hashCode ^
      googleCleanupStatus.hashCode ^
      thumbnailPath.hashCode ^
      previewPath.hashCode ^
      blurHash.hashCode ^
      isFavorite.hashCode ^
      isArchived.hashCode ^
      isTrashed.hashCode ^
      trashedTimestamp.hashCode ^
      isEncrypted.hashCode ^
      albumIds.hashCode ^
      deviceFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          localIdentifier == other.localIdentifier &&
          fileName == other.fileName &&
          filePath == other.filePath &&
          mimeType == other.mimeType &&
          mediaType == other.mediaType &&
          fileSizeBytes == other.fileSizeBytes &&
          sha256Hash == other.sha256Hash &&
          dateTaken == other.dateTaken &&
          dateAdded == other.dateAdded &&
          width == other.width &&
          height == other.height &&
          orientation == other.orientation &&
          durationMs == other.durationMs &&
          cameraMake == other.cameraMake &&
          cameraModel == other.cameraModel &&
          focalLength == other.focalLength &&
          aperture == other.aperture &&
          iso == other.iso &&
          exposureTime == other.exposureTime &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          geoCity == other.geoCity &&
          geoCountry == other.geoCountry &&
          syncStatus == other.syncStatus &&
          uploadProgress == other.uploadProgress &&
          errorMessage == other.errorMessage &&
          tgChannelId == other.tgChannelId &&
          tgMessageId == other.tgMessageId &&
          tgFileId == other.tgFileId &&
          tgAccessHash == other.tgAccessHash &&
          importedFromGooglePhotos == other.importedFromGooglePhotos &&
          googlePhotosMediaId == other.googlePhotosMediaId &&
          googleCleanupStatus == other.googleCleanupStatus &&
          thumbnailPath == other.thumbnailPath &&
          previewPath == other.previewPath &&
          blurHash == other.blurHash &&
          isFavorite == other.isFavorite &&
          isArchived == other.isArchived &&
          isTrashed == other.isTrashed &&
          trashedTimestamp == other.trashedTimestamp &&
          isEncrypted == other.isEncrypted &&
          albumIds == other.albumIds &&
          deviceFolder == other.deviceFolder;
}

class TelegramUser {
  final PlatformInt64 id;
  final String firstName;
  final String? lastName;
  final String? username;
  final String phone;
  final bool isPremium;

  const TelegramUser({
    required this.id,
    required this.firstName,
    this.lastName,
    this.username,
    required this.phone,
    required this.isPremium,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      firstName.hashCode ^
      lastName.hashCode ^
      username.hashCode ^
      phone.hashCode ^
      isPremium.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelegramUser &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          firstName == other.firstName &&
          lastName == other.lastName &&
          username == other.username &&
          phone == other.phone &&
          isPremium == other.isPremium;
}

class Upload {
  final String id;
  final String mediaId;
  final PlatformInt64? messageId;
  final String? fileId;
  final String? hashSha256;
  final String status;
  final PlatformInt64 retryCount;
  final String? lastError;
  final PlatformInt64 uploadedBytes;
  final PlatformInt64 totalBytes;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const Upload({
    required this.id,
    required this.mediaId,
    this.messageId,
    this.fileId,
    this.hashSha256,
    required this.status,
    required this.retryCount,
    this.lastError,
    required this.uploadedBytes,
    required this.totalBytes,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      mediaId.hashCode ^
      messageId.hashCode ^
      fileId.hashCode ^
      hashSha256.hashCode ^
      status.hashCode ^
      retryCount.hashCode ^
      lastError.hashCode ^
      uploadedBytes.hashCode ^
      totalBytes.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Upload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          mediaId == other.mediaId &&
          messageId == other.messageId &&
          fileId == other.fileId &&
          hashSha256 == other.hashSha256 &&
          status == other.status &&
          retryCount == other.retryCount &&
          lastError == other.lastError &&
          uploadedBytes == other.uploadedBytes &&
          totalBytes == other.totalBytes &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class UploadsSummary {
  final PlatformInt64 queuedCount;
  final PlatformInt64 queuedBytes;
  final PlatformInt64 uploadingCount;
  final PlatformInt64 uploadingBytes;
  final PlatformInt64 failedCount;
  final PlatformInt64 failedBytes;
  final PlatformInt64 backedUpCount;
  final PlatformInt64 backedUpBytes;

  const UploadsSummary({
    required this.queuedCount,
    required this.queuedBytes,
    required this.uploadingCount,
    required this.uploadingBytes,
    required this.failedCount,
    required this.failedBytes,
    required this.backedUpCount,
    required this.backedUpBytes,
  });

  @override
  int get hashCode =>
      queuedCount.hashCode ^
      queuedBytes.hashCode ^
      uploadingCount.hashCode ^
      uploadingBytes.hashCode ^
      failedCount.hashCode ^
      failedBytes.hashCode ^
      backedUpCount.hashCode ^
      backedUpBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadsSummary &&
          runtimeType == other.runtimeType &&
          queuedCount == other.queuedCount &&
          queuedBytes == other.queuedBytes &&
          uploadingCount == other.uploadingCount &&
          uploadingBytes == other.uploadingBytes &&
          failedCount == other.failedCount &&
          failedBytes == other.failedBytes &&
          backedUpCount == other.backedUpCount &&
          backedUpBytes == other.backedUpBytes;
}

class VaultInfo {
  final PlatformInt64? channelId;
  final String channelTitle;
  final bool isPrivate;
  final PlatformInt64 totalStorageUsedBytes;
  final PlatformInt64 totalBackedUpFiles;
  final PlatformInt64 lastSyncTimestamp;

  const VaultInfo({
    this.channelId,
    required this.channelTitle,
    required this.isPrivate,
    required this.totalStorageUsedBytes,
    required this.totalBackedUpFiles,
    required this.lastSyncTimestamp,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^
      channelTitle.hashCode ^
      isPrivate.hashCode ^
      totalStorageUsedBytes.hashCode ^
      totalBackedUpFiles.hashCode ^
      lastSyncTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultInfo &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          channelTitle == other.channelTitle &&
          isPrivate == other.isPrivate &&
          totalStorageUsedBytes == other.totalStorageUsedBytes &&
          totalBackedUpFiles == other.totalBackedUpFiles &&
          lastSyncTimestamp == other.lastSyncTimestamp;
}
