// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'mirror.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Check if there is an existing authorized session (cold start).
/// Tries to restore from DB if no in-memory client exists.
Future<bool> checkConnection({
  required TelegramHandle handle,
  required String appDataDir,
}) => RustLib.instance.api.crateApiTelegramCheckConnection(
  handle: handle,
  appDataDir: appDataDir,
);

/// Request OTP code for phone login.
Future<AuthCodeResult> authRequestCode({
  required TelegramHandle handle,
  required String phone,
  required int apiId,
  required String apiHash,
  required String appDataDir,
}) => RustLib.instance.api.crateApiTelegramAuthRequestCode(
  handle: handle,
  phone: phone,
  apiId: apiId,
  apiHash: apiHash,
  appDataDir: appDataDir,
);

/// Submit OTP code to sign in.
Future<AuthCodeResult> authSignIn({
  required TelegramHandle handle,
  required String code,
}) =>
    RustLib.instance.api.crateApiTelegramAuthSignIn(handle: handle, code: code);

/// Submit 2FA password.
Future<AuthCodeResult> authCheckPassword({
  required TelegramHandle handle,
  required String password,
}) => RustLib.instance.api.crateApiTelegramAuthCheckPassword(
  handle: handle,
  password: password,
);

/// Start QR code login flow. Returns `tg://login?token=...` URL.
Future<String> authQrLogin({
  required TelegramHandle handle,
  required int apiId,
  required String apiHash,
  required String appDataDir,
}) => RustLib.instance.api.crateApiTelegramAuthQrLogin(
  handle: handle,
  apiId: apiId,
  apiHash: apiHash,
  appDataDir: appDataDir,
);

/// Poll QR login status. Returns status: "authorized" or "waiting".
Future<AuthCodeResult> authQrPoll({required TelegramHandle handle}) =>
    RustLib.instance.api.crateApiTelegramAuthQrPoll(handle: handle);

/// Get current logged-in user info.
Future<TelegramUser?> getMe({required TelegramHandle handle}) =>
    RustLib.instance.api.crateApiTelegramGetMe(handle: handle);

/// Logout and delete session.
Future<bool> logout({
  required TelegramHandle handle,
  required String appDataDir,
}) => RustLib.instance.api.crateApiTelegramLogout(
  handle: handle,
  appDataDir: appDataDir,
);

/// Upload a single photo file to the Telegram vault channel.
/// Returns the Telegram message ID on success.
Future<PlatformInt64> uploadPhoto({
  required TelegramHandle handle,
  required String filePath,
  required String fileName,
  required String mimeType,
  required bool isVideo,
}) => RustLib.instance.api.crateApiTelegramUploadPhoto(
  handle: handle,
  filePath: filePath,
  fileName: fileName,
  mimeType: mimeType,
  isVideo: isVideo,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TelegramHandle>>
abstract class TelegramHandle implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Creates a new handle. Called once from Dart at app startup.
  static Future<TelegramHandle> newInstance() =>
      RustLib.instance.api.crateApiTelegramTelegramHandleNew();
}
